### ISSUE TITLE
Cannot locate SCDV.py

### ISSUE THREAD

**Issue by bernardmizzi** [vgupta123/SCDV-MS#1]
Good morning,

I would like to replicate your results but I cannot locate script SCDV.py.

Regards,
Bernard

**Comment by vgupta123** [comment]
Hi Bernald,

Apology, it renamed as scdv_ms.py

Yours Sincerely
Vivek Gupta
Graduate Student, School of Computing
University of Utah
https://vgupta123.github.io

**Comment by vgupta123** [comment]
ignore the readme and jump to 20newsgroup folder

run doc2vecC code in word2vec folder
then run word topic vectors
and finally train a SVM classifier

I will fix the issues soon once I get some time

**Comment by vgupta123** [comment]
Hi

I modified the readme so that you can now run the code. Reuters has some missing files, which I will fix soon by this weekend.

Thanks for pointing mistake.

Regards
Vivek Gupta
